#!/bin/bash
echo "Ready to push frontend to GitHub!"
echo "First, create a new repository on GitHub named: sendbird-healthcare-frontend"
echo ""
echo "Then run these commands:"
echo ""
echo "git remote add origin https://github.com/cgmartin0310/sendbird-healthcare-frontend.git"
echo "git push -u origin main"
echo ""
echo "After pushing, go to Render and:"
echo "1. Delete the current static site (if you created one)"
echo "2. Create a NEW static site"
echo "3. Connect the NEW frontend repository"
echo "4. Use these settings:"
echo "   - Build Command: npm install && npm run build"
echo "   - Publish Directory: dist"
echo "5. Add environment variable: VITE_SENDBIRD_APP_ID"
